// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-cTYswpttgWB68tOXILYWJJuawPj9A8',
    appId: '1:836642487055:android:41c7db05334346b8115c7a',
    messagingSenderId: '836642487055',
    projectId: 'sadardiri-mini-project',
    storageBucket: 'sadardiri-mini-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAx7wI9FYdDsKYBcfCJiv_Y2yZT4xZhxo',
    appId: '1:836642487055:ios:65f2ed60b20a6fdf115c7a',
    messagingSenderId: '836642487055',
    projectId: 'sadardiri-mini-project',
    storageBucket: 'sadardiri-mini-project.firebasestorage.app',
    iosBundleId: 'com.example.sadardiriMiniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAx7wI9FYdDsKYBcfCJiv_Y2yZT4xZhxo',
    appId: '1:836642487055:ios:65f2ed60b20a6fdf115c7a',
    messagingSenderId: '836642487055',
    projectId: 'sadardiri-mini-project',
    storageBucket: 'sadardiri-mini-project.firebasestorage.app',
    iosBundleId: 'com.example.sadardiriMiniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhqOhwpT4C_T-V9YmYxgh3J5hqhw7yGi8',
    appId: '1:836642487055:web:f638b3910e49f5de115c7a',
    messagingSenderId: '836642487055',
    projectId: 'sadardiri-mini-project',
    authDomain: 'sadardiri-mini-project.firebaseapp.com',
    storageBucket: 'sadardiri-mini-project.firebasestorage.app',
  );
}
